# Default configuration file

# Hardware
cpu:
  limit: 2  # Global CPU limit for all operations

# Important directory and file paths
dataset_list: "./datasets.txt"
dataset_info: "./datasets.tsv"

project_dir: "../../test"
manual_metadata_dir: "../../../manual_metadata"

blast_db_dir: "./blast/silva_16s/SILVA_16S_db"

# ENA API
ena_email: "macgregor@berkeley.edu"

# Toggle what parts to run
upstream: False
downstream: True

# Part I: Upstream
# ================

# Toggle if PCR primers used are manually provided or predicted
pcr_primers_mode: "manual"

# Target 16S subfragment
target_subfragment_mode: "any"

# Toggle sequence quality/validation tools
run_validate_16s: False
run_fastqc: False
run_seqkit: False

validate_16s:
  n_runs: 10
  run_targets:
    - '16S'
    - 'unknown'

cutadapt:
  start_trim: 0
  end_trim: 0
  start_q_cutoff: 30
  end_q_cutoff: 15
  min_seq_length: 150
  n_cores: 16

# Toggle CutAdapt outside of QIIME
run_cutadapt: False

# QIIME settings
qiime2:
  per_dataset:
    script_path: "../src/workflow_16s/qiime/workflows/per_dataset_run.py"
    hard_rerun: False
    trim:
      run: True
    denoise:
      chimera_method: "consensus"
      denoise_algorithm: "DADA2"
    taxonomy:
      classifier_dir: "./classifier/silva-138-99-515-806"
      classifier: "silva-138-99-515-806"
      classify_method: "sklearn"
    filter:
      retain_threshold: 80
    
clean_fastq: True

# Part II. Downstream
# ===================
features:
  filter: True
  normalize: True
  clr_transform: True
  presence_absence: True

# Statistical Analyses
stats:
  raw:
    ttest: False              # ❌ compositionality violates assumptions
    mwu_bonferroni: False #True      # ✅ non-parametric alternative
    kruskal_bonferroni: False #True
  presence_absence:
    fisher: False #True              # ✅ ideal for binary data
    ttest: False              # ❌ designed for continuous data
    mwu_bonferroni: False     # ❌ not designed for binary data
    kruskal_bonferroni: False
  filtered:
    ttest: False              # ❌ compositionality violates assumptions
    mwu_bonferroni: False #True
    kruskal_bonferroni: False #True
  normalized:
    ttest: False #True               # ✅ can be used after proper normalization
    mwu_bonferroni: False #True      # ✅ still valuable for robustness
    kruskal_bonferroni: False #True
  clr_transformed:
    ttest: False #True               # ✅ CLR addresses compositionality
    mwu_bonferroni: False #True      # ✅ good alternative for non-normal distributions
    kruskal_bonferroni: True

# Alpha Diversity
alpha_diversity:
  enabled: False #true
  metrics:  # Metrics to calculate
    - shannon
    - observed_features
    - simpson
  parametric: false  # Statistical test type
  generate_plots: true  # Enable/disable plot generation
  tables:
    raw:  # Table type
      enabled: true
      levels:  # Taxonomic levels
        - genus
        - family
    normalized:
      enabled: true
      levels: 
        - genus
    
# Beta Diversity + Ordination
ordination:
  max_workers: 1  # Max concurrent ordination tasks
  cpu_limit: 1    # CPU cores per ordination method
  raw:
    pca: False 
    pcoa: False #True
    pcoa_metric: "braycurtis"
    tsne: False
    umap: False
  presence_absence:
    pca: False
    pcoa: False #True
    pcoa_metric: "jaccard"
    tsne: False #True
    umap: False #True
  filtered:
    pca: False
    pcoa: False #True
    pcoa_metric: "braycurtis"
    tsne: False #True
    umap: False #True
  normalized:
    pca: False #True
    pcoa: False #True
    pcoa_metric: "braycurtis"
    tsne: False #True
    umap: False #True
  clr_transformed:
    pca: True
    pcoa: False #True
    pcoa_metric: "euclidean"
    tsne: False #True
    umap: False #True

# Functional Prediction
faprotax: True

# Figures
figures:
  map: True
  color_columns: 
    - "dataset_name"
    - "nuclear_contamination_status"
    - "env_feature"
    - "env_material"
    - "country"

# Machine Learning
run_ml: False #True
ml:
  table_types:
    - 'clr_transformed'
  levels:
    - 'genus'
  methods:
    - 'rfe'
    #- 'select_k_best'
    #- 'chi_squared'
    #- 'lasso'
    #- 'shap'
  num_features: 500
  step_size: 100
  permutation_importance: True
  n_threads: 4
