# Default configuration file

ENA:
  email: "macgregor@berkeley.edu"

Dataset List: "./datasets.txt"
Dataset Information: "./datasets.tsv"

Manual Metadata Directory: "../../manual_metadata"

Project Directory: "../../test"

PCR Primers: "manual"
Target Subfragment: "any"

Sequence Validation:
  n_runs: 10
  run_targets:
    - '16S'
    - 'unknown'
    
BLAST:
  path: "./blast/silva_16s/SILVA_16S_db"
    
FastQC:
  run: False
  
SeqKit:
  run: False
  
Cutadapt:
  run: False
  start_trim: 0
  end_trim: 0
  start_q_cutoff: 30
  end_q_cutoff: 15
  min_seq_length: 150
  cores: 16
  
QIIME 2:
  Per-Dataset:
    path: "../src/workflow_16s/qiime/workflows/per_dataset_run.py"
    hard_rerun: False
    n_threads: 32
    Trim Sequences:
      run: True
      trim_length: 250
      n_cores: 32
      save_intermediates: True
    Denoise Sequences:
      chimera_method: "consensus"
      denoise_algorithm: "DADA2"
      n_threads: 16
      trim_left_f: 0
      trim_left_r: 0
      trunc_q: 2
      max_ee: 2
      max_ee_f: 2
      max_ee_r: 2
    Taxonomic Classification:
      run: True
      hard_rerun: True
      classifier_dir: "./classifier/silva-138-99-515-806"
      classifier: "silva-138-99-515-806"
      classify_method: "sklearn"
      maxaccepts: 50
      perc_identity: 0.99
      query_cov: 0.9
    Filter:
      retain_threshold: 80
    
Clean Up FASTQ: True
