
ENA:
  email: "macgregor@berkeley.edu"

# List of datasets
Dataset List: "./datasets.txt"
# Experimental details for each dataset
Dataset Information: "./datasets.tsv"

# The main directory for files to be written to
Project Directory: "../../test"

# The directory where manual metadata files are stored as TSVs
Manual Metadata Directory: "../../manual_metadata"

# How to determine what PCR primers to use
PCR Primers: "manual"
# What target subfragment sequences will be trimmed to
# If 'any': use dataset-specific PCR primers to trim, compare at the genera level downstream
# Otherwise, select for datasets who target subfragment(s) include the specified subfragment,
# use standard primers for the specified subfragment to trim, compare at the ASV level downstream
Target Subfragment: "any"

Clean Up FASTQ: True

# Sequence Validation Parameters
Sequence Validation:
  n_runs: 10
  run_targets:
    - '16S'
    - 'unknown'
    
# BLAST Database Parameters
BLAST:
  path: "./blast/silva_16s/SILVA_16S_db"
    
# FastQC Processing Parameters
FastQC:
  run: False
  
SeqKit:
  run: False
  
Cutadapt:
  run: False
  start_trim: 0
  end_trim: 0
  start_q_cutoff: 30
  end_q_cutoff: 15
  min_seq_length: 150
  cores: 16
  
# QIIME2 Processing Parameters
QIIME 2:
  Per-Dataset:
    path: "../src/workflow_16s/qiime/workflows/per_dataset_run.py"
    # Toggles whether to rerun per-dataset QIIME2 processing, regardless of whether output files already exist.
    hard_rerun: True
    n_threads: 32
    Trim Sequences:
      # [QIIME 2][Trim Sequences][run] should be False if [Cutadapt][run] is True
      run: True
      trim_length: 250
      n_cores: 32
      save_intermediates: True
    Denoise Sequences:
      chimera_method: "consensus"
      denoise_algorithm: "DADA2"
      n_threads: 32
      trim_left_f: 0
      trim_left_r: 0
      trunc_q: 2
      max_ee: 2
      max_ee_f: 2
      max_ee_r: 2
    # Parameters for per-dataset taxonomic classification
    Taxonomic Classification:
      run: True
      hard_rerun: True
      classifier_dir: "./classifier/silva-138-99-515-806"
      classifier: "silva-138-99-515-806"
      classify_method: "sklearn"
      maxaccepts: 50
      perc_identity: 0.99
      query_cov: 0.9
    Filter:
      retain_threshold: 80
    
