# Default configuration file

# Hardware
cpu:
  limit: 16  # Global CPU limit for all operations

# Important directory and file paths
dataset_list: "./datasets.txt"
dataset_info: "./datasets.tsv"

project_dir: "../../test"
manual_metadata_dir: "../../../manual_metadata"

blast_db_dir: "./blast/silva_16s/SILVA_16S_db"

# ENA API
ena_email: "macgregor@berkeley.edu"

# Toggle what parts to run
upstream: False
downstream: True

# Part I: Upstream
# ================

# Toggle if PCR primers used are manually provided or predicted
pcr_primers_mode: "manual"

# Target 16S subfragment
target_subfragment_mode: "any"

# Toggle sequence quality/validation tools
run_validate_16s: False
run_fastqc: False
run_seqkit: False

validate_16s:
  n_runs: 10
  run_targets:
    - '16S'
    - 'unknown'

cutadapt:
  start_trim: 0
  end_trim: 0
  start_q_cutoff: 30
  end_q_cutoff: 15
  min_seq_length: 150
  n_cores: 16

# Toggle CutAdapt outside of QIIME
run_cutadapt: False

# QIIME settings
qiime2:
  per_dataset:
    script_path: "../src/workflow_16s/qiime/workflows/per_dataset_run.py"
    hard_rerun: False
    trim:
      run: True
    denoise:
      chimera_method: "consensus"
      denoise_algorithm: "DADA2"
    taxonomy:
      classifier_dir: "./classifier/silva-138-99-515-806"
      classifier: "silva-138-99-515-806"
      classify_method: "sklearn"
    filter:
      retain_threshold: 80
    
clean_fastq: True

# Part II. Downstream
# ===================

group_column: "nuclear_contamination_status"
group_column_values: 
  - True
  - False
  
# Feature Table Processing
features:
  filter: True
  normalize: True
  clr_transform: True
  presence_absence: True

# Statistical Analyses
stats:
  enabled: True
  tables:
    raw:
      enabled: True
      tests:
        #- "fisher"
        #- "ttest"                # ❌ compositionality violates assumptions
        - "mwu_bonferroni"        # ✅ non-parametric alternative
        - "kruskal_bonferroni"
    presence_absence:
      enabled: True
      tests:
        - "fisher"                # ✅ ideal for binary data
        #- "ttest"                # ❌ designed for continuous data
        #- "mwu_bonferroni"       # ❌ not designed for binary data
        #- "kruskal_bonferroni"
    filtered:
      enabled: True
      tests:
        #- "fisher"
        #- "ttest"                # ❌ compositionality violates assumptions
        - "mwu_bonferroni"
        - "kruskal_bonferroni"
    normalized:
      enabled: True
      tests:
        #- "fisher"
        - "ttest"                 # ✅ can be used after proper normalization
        - "mwu_bonferroni"        # ✅ still valuable for robustness
        - "kruskal_bonferroni"
    clr_transformed:
      enabled: True
      tests:
        #- "fisher"
        - "ttest"                 # ✅ CLR addresses compositionality
        - "mwu_bonferroni"        # ✅ good alternative for non-normal distributions
        - "kruskal_bonferroni"

# Alpha Diversity
alpha_diversity:
  enabled: True
  tables: # Table type
    raw:  
      enabled: True
      levels:  # Taxonomic levels
        #- 'genus'
        - 'family'
        - 'class'
    normalized:
      enabled: True
      levels: 
        #- 'genus'
        - 'family'
  metrics:  # Metrics to calculate
    - 'shannon'
    - 'observed_features'
    - 'simpson'
    - 'pielou_evenness'
    #- 'chao1'
    #- 'ace'
    #- 'gini_index'
    #- 'goods_coverage'
    - 'heip_evenness' 
    #- 'dominance'
  parametric: False  # Statistical test type
  plots: 
    enabled: True  # Enable/disable plot generation
    add_points: True
    add_stat_annot: True
    effect_size_threshold: 0.5
  correlation_analysis: 
    enabled: False #True
    max_categories: 20       # Max unique values for categorical variables
    min_group_size: 5        # Min samples per group for valid comparison
    top_n_correlations: 20          # Number of top associations to show
    
# Beta Diversity + Ordination
ordination:
  enabled: True
  max_workers: 2   # Max concurrent ordination tasks
  cpu_limit: 16    # CPU cores per ordination method
  tables:
    raw:
      enabled: True
      pcoa_metric: "braycurtis"
      methods:
        #- "pca"
        - "pcoa"
        #- "tsne"
        #- "umap"
      levels:
        #- 'genus'
        - 'family'
        - 'class'
    filtered:
      enabled: True
      pcoa_metric: "braycurtis"
      methods:
        #- "pca"
        - "pcoa"
        - "tsne"
        - "umap"
      levels:
        - 'phylum'
    normalized:
      enabled: True
      pcoa_metric: "braycurtis"
      methods:
        - "pca"
        - "pcoa"
        - "tsne"
        - "umap"
      levels:
        - 'phylum'
    clr_transformed:
      enabled: True
      pcoa_metric: "euclidean"
      methods:
        - "pca"
        - "pcoa"
        - "tsne"
        - "umap"
      levels:
        - 'phylum'
    presence_absence:
      enabled: True
      pcoa_metric: "jaccard"
      methods:
        #- "pca"
        - "pcoa"
        - "tsne"
        - "umap"
      levels:
        - 'phylum'

# Functional Prediction
faprotax: True

# Figures
figures:
  map: True
  color_columns: 
    - "dataset_name"
    - "nuclear_contamination_status"
    - "env_feature"
    - "env_material"
    - "country"

# Violin Plots of Top Important Features
violin_plots: 
  enabled: True
  n: 50  # Number of features to plot per category

# Machine Learning
ml:
  enabled: True
  tables:
    raw:
      enabled: False
      levels:
      #- 'genus'
      #- 'family'
      #- 'order'
      #- 'class'
      - 'phylum'
    methods:
      - 'rfe'
      #- 'select_k_best'
      #- 'chi_squared'
      #- 'lasso'
      #- 'shap'
    filtered:
      enabled: False
      levels:
      #- 'genus'
      #- 'family'
      #- 'order'
      #- 'class'
      - 'phylum'
    methods:
      - 'rfe'
      #- 'select_k_best'
      #- 'chi_squared'
      #- 'lasso'
      #- 'shap'
    normalized:
      enabled: True
      levels:
      #- 'genus'
      #- 'family'
      #- 'order'
      #- 'class'
      - 'phylum'
    methods:
      - 'rfe'
      #- 'select_k_best'
      #- 'chi_squared'
      #- 'lasso'
      #- 'shap'
    clr_transformed:
      enabled: True
      levels:
      #- 'genus'
      #- 'family'
      #- 'order'
      #- 'class'
      - 'phylum'
    methods:
      - 'rfe'
      #- 'select_k_best'
      #- 'chi_squared'
      #- 'lasso'
      #- 'shap'
    presence_absence:
      enabled: True
      levels:
      #- 'genus'
      #- 'family'
      #- 'order'
      #- 'class'
      - 'phylum'
    methods:
      - 'rfe'
      #- 'select_k_best'
      #- 'chi_squared'
      #- 'lasso'
      #- 'shap'
  num_features: 500
  step_size: 100
  permutation_importance: 
    enabled: True
  n_threads: 16
  plots:
    enabled: True
